data: data/raw/climate/weatherHistory_simple.csv
target: Temperature (C)
date: Formatted Date
features: 
time_id:
start_time_id:
delimiter: ','
split_feature: 
dir_as_feature: 0
split_dir_feature: 0
time_format: 
granularity: 10

year_start:
year_end:
month_start:
month_end:
day_start:
day_end:
hour_start:
hour_end:
minute_start:
minute_end: