data: .\data\traffic\raw\a_year-by_id\23599.csv
target: speed
date: date
time_id: time_id
start_time_id: 240
features: current_geopath_id
delimiter: "|"
split_feature: current_geopath_id # or None
dir_as_feature: 0
split_dir_feature: 0
time_format: 

year_start:
year_end:
month_start:
month_end:
day_start:
day_end:
hour_start: 4
hour_end: 23
minute_start:
minute_end:
