data: 
  - .\data\raw\traffic\a_year-by_id-new\9093.csv
  - .\data\raw\traffic\a_year-by_id-new\531.csv
  - .\data\raw\traffic\a_year-by_id-new\532.csv
  - .\data\raw\traffic\a_year-by_id-new\9092.csv
  - .\data\raw\traffic\a_year-by_id-new\8432.csv
  - .\data\raw\traffic\a_year-by_id-new\3872.csv
  - .\data\raw\traffic\a_year-by_id-new\2859.csv
  - .\data\raw\traffic\a_year-by_id-new\287.csv
  - .\data\raw\traffic\a_year-by_id-new\288.csv
  - .\data\raw\traffic\a_year-by_id-new\289.csv
  - .\data\raw\traffic\a_year-by_id-new\533.csv
  - .\data\raw\traffic\a_year-by_id-new\534.csv
  - .\data\raw\traffic\a_year-by_id-new\587.csv
  - .\data\raw\traffic\a_year-by_id-new\588.csv
  - .\data\raw\traffic\a_year-by_id-new\642.csv
  - .\data\raw\traffic\a_year-by_id-new\886.csv
  - .\data\raw\traffic\a_year-by_id-new\887.csv
  - .\data\raw\traffic\a_year-by_id-new\946.csv
  - .\data\raw\traffic\a_year-by_id-new\947.csv
  - .\data\raw\traffic\a_year-by_id-new\948.csv
  - .\data\raw\traffic\a_year-by_id-new\1217.csv
  - .\data\raw\traffic\a_year-by_id-new\1218.csv
  - .\data\raw\traffic\a_year-by_id-new\1268.csv
  - .\data\raw\traffic\a_year-by_id-new\1269.csv
  - .\data\raw\traffic\a_year-by_id-new\1270.csv
  - .\data\raw\traffic\a_year-by_id-new\1298.csv
  - .\data\raw\traffic\a_year-by_id-new\1299.csv
  - .\data\raw\traffic\a_year-by_id-new\1310.csv
  - .\data\raw\traffic\a_year-by_id-new\1311.csv
  - .\data\raw\traffic\a_year-by_id-new\1455.csv
  - .\data\raw\traffic\a_year-by_id-new\1466.csv
  - .\data\raw\traffic\a_year-by_id-new\1510.csv
  - .\data\raw\traffic\a_year-by_id-new\1559.csv
  - .\data\raw\traffic\a_year-by_id-new\2077.csv
  - .\data\raw\traffic\a_year-by_id-new\2266.csv
  - .\data\raw\traffic\a_year-by_id-new\2267.csv
  - .\data\raw\traffic\a_year-by_id-new\2314.csv
  - .\data\raw\traffic\a_year-by_id-new\2378.csv
  - .\data\raw\traffic\a_year-by_id-new\2476.csv
  - .\data\raw\traffic\a_year-by_id-new\2477.csv
  - .\data\raw\traffic\a_year-by_id-new\2478.csv
  - .\data\raw\traffic\a_year-by_id-new\2479.csv
  - .\data\raw\traffic\a_year-by_id-new\2480.csv
  - .\data\raw\traffic\a_year-by_id-new\2481.csv
  - .\data\raw\traffic\a_year-by_id-new\2482.csv
  - .\data\raw\traffic\a_year-by_id-new\2521.csv
  - .\data\raw\traffic\a_year-by_id-new\2860.csv
  - .\data\raw\traffic\a_year-by_id-new\2861.csv
  - .\data\raw\traffic\a_year-by_id-new\2869.csv
  - .\data\raw\traffic\a_year-by_id-new\2982.csv
  - .\data\raw\traffic\a_year-by_id-new\2983.csv
  - .\data\raw\traffic\a_year-by_id-new\2984.csv
  - .\data\raw\traffic\a_year-by_id-new\3009.csv
  - .\data\raw\traffic\a_year-by_id-new\3010.csv
  - .\data\raw\traffic\a_year-by_id-new\3011.csv
  - .\data\raw\traffic\a_year-by_id-new\3102.csv
  - .\data\raw\traffic\a_year-by_id-new\3103.csv
  - .\data\raw\traffic\a_year-by_id-new\3104.csv
  - .\data\raw\traffic\a_year-by_id-new\3105.csv
  - .\data\raw\traffic\a_year-by_id-new\3106.csv
  - .\data\raw\traffic\a_year-by_id-new\3107.csv
  - .\data\raw\traffic\a_year-by_id-new\3108.csv
  - .\data\raw\traffic\a_year-by_id-new\3109.csv
  - .\data\raw\traffic\a_year-by_id-new\3140.csv
  - .\data\raw\traffic\a_year-by_id-new\3141.csv
  - .\data\raw\traffic\a_year-by_id-new\3142.csv
  - .\data\raw\traffic\a_year-by_id-new\3143.csv
  - .\data\raw\traffic\a_year-by_id-new\3367.csv
  - .\data\raw\traffic\a_year-by_id-new\3368.csv
  - .\data\raw\traffic\a_year-by_id-new\3369.csv
  - .\data\raw\traffic\a_year-by_id-new\3370.csv
  - .\data\raw\traffic\a_year-by_id-new\3371.csv
  - .\data\raw\traffic\a_year-by_id-new\3372.csv
  - .\data\raw\traffic\a_year-by_id-new\3373.csv
  - .\data\raw\traffic\a_year-by_id-new\3374.csv
  - .\data\raw\traffic\a_year-by_id-new\3375.csv
  - .\data\raw\traffic\a_year-by_id-new\3376.csv
  - .\data\raw\traffic\a_year-by_id-new\3377.csv
  - .\data\raw\traffic\a_year-by_id-new\3378.csv
  - .\data\raw\traffic\a_year-by_id-new\3379.csv
  - .\data\raw\traffic\a_year-by_id-new\3380.csv
  - .\data\raw\traffic\a_year-by_id-new\3381.csv
  - .\data\raw\traffic\a_year-by_id-new\3382.csv
  - .\data\raw\traffic\a_year-by_id-new\3383.csv
  - .\data\raw\traffic\a_year-by_id-new\3384.csv
  - .\data\raw\traffic\a_year-by_id-new\3385.csv
  - .\data\raw\traffic\a_year-by_id-new\3386.csv
  - .\data\raw\traffic\a_year-by_id-new\3387.csv
  - .\data\raw\traffic\a_year-by_id-new\3388.csv
  - .\data\raw\traffic\a_year-by_id-new\3389.csv
  - .\data\raw\traffic\a_year-by_id-new\3390.csv
  - .\data\raw\traffic\a_year-by_id-new\3410.csv
  - .\data\raw\traffic\a_year-by_id-new\3411.csv
  - .\data\raw\traffic\a_year-by_id-new\3412.csv
  - .\data\raw\traffic\a_year-by_id-new\3413.csv
  - .\data\raw\traffic\a_year-by_id-new\3414.csv
  - .\data\raw\traffic\a_year-by_id-new\3447.csv
  - .\data\raw\traffic\a_year-by_id-new\3448.csv
  - .\data\raw\traffic\a_year-by_id-new\3449.csv
  - .\data\raw\traffic\a_year-by_id-new\3450.csv
  - .\data\raw\traffic\a_year-by_id-new\3452.csv
  - .\data\raw\traffic\a_year-by_id-new\3453.csv
  - .\data\raw\traffic\a_year-by_id-new\3454.csv
  - .\data\raw\traffic\a_year-by_id-new\3546.csv
  - .\data\raw\traffic\a_year-by_id-new\3547.csv
  - .\data\raw\traffic\a_year-by_id-new\3692.csv
  - .\data\raw\traffic\a_year-by_id-new\3693.csv
  - .\data\raw\traffic\a_year-by_id-new\3759.csv
  - .\data\raw\traffic\a_year-by_id-new\3760.csv
  - .\data\raw\traffic\a_year-by_id-new\3780.csv
  - .\data\raw\traffic\a_year-by_id-new\3781.csv
  - .\data\raw\traffic\a_year-by_id-new\3782.csv
  - .\data\raw\traffic\a_year-by_id-new\3838.csv
  - .\data\raw\traffic\a_year-by_id-new\3839.csv
  - .\data\raw\traffic\a_year-by_id-new\3840.csv
  - .\data\raw\traffic\a_year-by_id-new\3870.csv
  - .\data\raw\traffic\a_year-by_id-new\3871.csv
  - .\data\raw\traffic\a_year-by_id-new\3923.csv
  - .\data\raw\traffic\a_year-by_id-new\3924.csv
  - .\data\raw\traffic\a_year-by_id-new\3952.csv
  - .\data\raw\traffic\a_year-by_id-new\3953.csv
  - .\data\raw\traffic\a_year-by_id-new\3954.csv
  - .\data\raw\traffic\a_year-by_id-new\3955.csv
  - .\data\raw\traffic\a_year-by_id-new\3956.csv
  - .\data\raw\traffic\a_year-by_id-new\3957.csv
  - .\data\raw\traffic\a_year-by_id-new\4105.csv
  - .\data\raw\traffic\a_year-by_id-new\4106.csv
  - .\data\raw\traffic\a_year-by_id-new\4107.csv
  - .\data\raw\traffic\a_year-by_id-new\4108.csv
  - .\data\raw\traffic\a_year-by_id-new\4121.csv
  - .\data\raw\traffic\a_year-by_id-new\4181.csv
  - .\data\raw\traffic\a_year-by_id-new\4224.csv
  - .\data\raw\traffic\a_year-by_id-new\4225.csv
  - .\data\raw\traffic\a_year-by_id-new\4414.csv
  - .\data\raw\traffic\a_year-by_id-new\4509.csv
  - .\data\raw\traffic\a_year-by_id-new\4510.csv
  - .\data\raw\traffic\a_year-by_id-new\4511.csv
  - .\data\raw\traffic\a_year-by_id-new\4512.csv
  - .\data\raw\traffic\a_year-by_id-new\4513.csv
  - .\data\raw\traffic\a_year-by_id-new\4514.csv
  - .\data\raw\traffic\a_year-by_id-new\4515.csv
  - .\data\raw\traffic\a_year-by_id-new\4550.csv
  - .\data\raw\traffic\a_year-by_id-new\4551.csv
  - .\data\raw\traffic\a_year-by_id-new\4552.csv
  - .\data\raw\traffic\a_year-by_id-new\4553.csv
  - .\data\raw\traffic\a_year-by_id-new\4662.csv
  - .\data\raw\traffic\a_year-by_id-new\4663.csv
  - .\data\raw\traffic\a_year-by_id-new\4664.csv
  - .\data\raw\traffic\a_year-by_id-new\4665.csv
  - .\data\raw\traffic\a_year-by_id-new\4931.csv
  - .\data\raw\traffic\a_year-by_id-new\5116.csv
  - .\data\raw\traffic\a_year-by_id-new\5117.csv
  - .\data\raw\traffic\a_year-by_id-new\5346.csv
  - .\data\raw\traffic\a_year-by_id-new\5388.csv
  - .\data\raw\traffic\a_year-by_id-new\5389.csv
  - .\data\raw\traffic\a_year-by_id-new\5390.csv
  - .\data\raw\traffic\a_year-by_id-new\5501.csv
  - .\data\raw\traffic\a_year-by_id-new\5741.csv
  - .\data\raw\traffic\a_year-by_id-new\5742.csv
  - .\data\raw\traffic\a_year-by_id-new\5743.csv
  - .\data\raw\traffic\a_year-by_id-new\5744.csv
  - .\data\raw\traffic\a_year-by_id-new\5764.csv
  - .\data\raw\traffic\a_year-by_id-new\5765.csv
  - .\data\raw\traffic\a_year-by_id-new\5780.csv
  - .\data\raw\traffic\a_year-by_id-new\5835.csv
  - .\data\raw\traffic\a_year-by_id-new\6332.csv
  - .\data\raw\traffic\a_year-by_id-new\6498.csv
  - .\data\raw\traffic\a_year-by_id-new\6499.csv
  - .\data\raw\traffic\a_year-by_id-new\6500.csv
  - .\data\raw\traffic\a_year-by_id-new\6501.csv
  - .\data\raw\traffic\a_year-by_id-new\6502.csv
  - .\data\raw\traffic\a_year-by_id-new\6553.csv
  - .\data\raw\traffic\a_year-by_id-new\6554.csv
  - .\data\raw\traffic\a_year-by_id-new\6864.csv
  - .\data\raw\traffic\a_year-by_id-new\6994.csv
  - .\data\raw\traffic\a_year-by_id-new\7164.csv
  - .\data\raw\traffic\a_year-by_id-new\7165.csv
  - .\data\raw\traffic\a_year-by_id-new\7166.csv
  - .\data\raw\traffic\a_year-by_id-new\7541.csv
  - .\data\raw\traffic\a_year-by_id-new\7578.csv
  - .\data\raw\traffic\a_year-by_id-new\7579.csv
  - .\data\raw\traffic\a_year-by_id-new\7580.csv
  - .\data\raw\traffic\a_year-by_id-new\7581.csv
  - .\data\raw\traffic\a_year-by_id-new\7582.csv
  - .\data\raw\traffic\a_year-by_id-new\7583.csv
  - .\data\raw\traffic\a_year-by_id-new\7584.csv
  - .\data\raw\traffic\a_year-by_id-new\7585.csv
  - .\data\raw\traffic\a_year-by_id-new\7654.csv
  - .\data\raw\traffic\a_year-by_id-new\7655.csv
  - .\data\raw\traffic\a_year-by_id-new\7656.csv
  - .\data\raw\traffic\a_year-by_id-new\7657.csv
  - .\data\raw\traffic\a_year-by_id-new\7658.csv
  - .\data\raw\traffic\a_year-by_id-new\7659.csv
  - .\data\raw\traffic\a_year-by_id-new\7665.csv
  - .\data\raw\traffic\a_year-by_id-new\7666.csv
  - .\data\raw\traffic\a_year-by_id-new\7667.csv
  - .\data\raw\traffic\a_year-by_id-new\7769.csv
  - .\data\raw\traffic\a_year-by_id-new\7770.csv
  - .\data\raw\traffic\a_year-by_id-new\7771.csv
  - .\data\raw\traffic\a_year-by_id-new\7772.csv
  - .\data\raw\traffic\a_year-by_id-new\7773.csv
  - .\data\raw\traffic\a_year-by_id-new\7774.csv
  - .\data\raw\traffic\a_year-by_id-new\7775.csv
  - .\data\raw\traffic\a_year-by_id-new\7776.csv
  - .\data\raw\traffic\a_year-by_id-new\7777.csv
  - .\data\raw\traffic\a_year-by_id-new\7778.csv
  - .\data\raw\traffic\a_year-by_id-new\7779.csv
  - .\data\raw\traffic\a_year-by_id-new\7780.csv
  - .\data\raw\traffic\a_year-by_id-new\7781.csv
  - .\data\raw\traffic\a_year-by_id-new\7782.csv
  - .\data\raw\traffic\a_year-by_id-new\7783.csv
  - .\data\raw\traffic\a_year-by_id-new\7784.csv
  - .\data\raw\traffic\a_year-by_id-new\7785.csv
  - .\data\raw\traffic\a_year-by_id-new\7806.csv
  - .\data\raw\traffic\a_year-by_id-new\7807.csv
  - .\data\raw\traffic\a_year-by_id-new\7808.csv
  - .\data\raw\traffic\a_year-by_id-new\7809.csv
  - .\data\raw\traffic\a_year-by_id-new\7810.csv
  - .\data\raw\traffic\a_year-by_id-new\7811.csv
  - .\data\raw\traffic\a_year-by_id-new\7812.csv
  - .\data\raw\traffic\a_year-by_id-new\7813.csv
  - .\data\raw\traffic\a_year-by_id-new\7814.csv
  - .\data\raw\traffic\a_year-by_id-new\7852.csv
  - .\data\raw\traffic\a_year-by_id-new\7853.csv
  - .\data\raw\traffic\a_year-by_id-new\8117.csv
  - .\data\raw\traffic\a_year-by_id-new\8125.csv
  - .\data\raw\traffic\a_year-by_id-new\8126.csv
  - .\data\raw\traffic\a_year-by_id-new\8127.csv
  - .\data\raw\traffic\a_year-by_id-new\8141.csv
  - .\data\raw\traffic\a_year-by_id-new\8282.csv
  - .\data\raw\traffic\a_year-by_id-new\8388.csv
  - .\data\raw\traffic\a_year-by_id-new\8389.csv
  - .\data\raw\traffic\a_year-by_id-new\8390.csv
  - .\data\raw\traffic\a_year-by_id-new\8391.csv
  - .\data\raw\traffic\a_year-by_id-new\8474.csv
  - .\data\raw\traffic\a_year-by_id-new\8514.csv
  - .\data\raw\traffic\a_year-by_id-new\8515.csv
  - .\data\raw\traffic\a_year-by_id-new\8578.csv
  - .\data\raw\traffic\a_year-by_id-new\8579.csv
  - .\data\raw\traffic\a_year-by_id-new\8580.csv
  - .\data\raw\traffic\a_year-by_id-new\8584.csv
  - .\data\raw\traffic\a_year-by_id-new\8585.csv
  - .\data\raw\traffic\a_year-by_id-new\8586.csv
  - .\data\raw\traffic\a_year-by_id-new\8587.csv
  - .\data\raw\traffic\a_year-by_id-new\8641.csv
  - .\data\raw\traffic\a_year-by_id-new\8642.csv
  - .\data\raw\traffic\a_year-by_id-new\8643.csv
  - .\data\raw\traffic\a_year-by_id-new\8644.csv
  - .\data\raw\traffic\a_year-by_id-new\8645.csv
  - .\data\raw\traffic\a_year-by_id-new\8646.csv
  - .\data\raw\traffic\a_year-by_id-new\8647.csv
  - .\data\raw\traffic\a_year-by_id-new\8648.csv
  - .\data\raw\traffic\a_year-by_id-new\8649.csv
  - .\data\raw\traffic\a_year-by_id-new\8650.csv
  - .\data\raw\traffic\a_year-by_id-new\8651.csv
  - .\data\raw\traffic\a_year-by_id-new\8652.csv
  - .\data\raw\traffic\a_year-by_id-new\8653.csv
  - .\data\raw\traffic\a_year-by_id-new\8654.csv
  - .\data\raw\traffic\a_year-by_id-new\8655.csv
  - .\data\raw\traffic\a_year-by_id-new\8656.csv
  - .\data\raw\traffic\a_year-by_id-new\8657.csv
  - .\data\raw\traffic\a_year-by_id-new\8658.csv
  - .\data\raw\traffic\a_year-by_id-new\8659.csv
  - .\data\raw\traffic\a_year-by_id-new\8660.csv
  - .\data\raw\traffic\a_year-by_id-new\8661.csv
  - .\data\raw\traffic\a_year-by_id-new\8662.csv
  - .\data\raw\traffic\a_year-by_id-new\8679.csv
  - .\data\raw\traffic\a_year-by_id-new\8680.csv
  - .\data\raw\traffic\a_year-by_id-new\8681.csv
  - .\data\raw\traffic\a_year-by_id-new\8729.csv
  - .\data\raw\traffic\a_year-by_id-new\8776.csv
  - .\data\raw\traffic\a_year-by_id-new\8777.csv
  - .\data\raw\traffic\a_year-by_id-new\8778.csv
  - .\data\raw\traffic\a_year-by_id-new\8786.csv
  - .\data\raw\traffic\a_year-by_id-new\8787.csv
  - .\data\raw\traffic\a_year-by_id-new\8814.csv
  - .\data\raw\traffic\a_year-by_id-new\8920.csv
  - .\data\raw\traffic\a_year-by_id-new\8925.csv
  - .\data\raw\traffic\a_year-by_id-new\8926.csv
  - .\data\raw\traffic\a_year-by_id-new\8927.csv
  - .\data\raw\traffic\a_year-by_id-new\8928.csv
  - .\data\raw\traffic\a_year-by_id-new\8929.csv
  - .\data\raw\traffic\a_year-by_id-new\9038.csv
  - .\data\raw\traffic\a_year-by_id-new\9039.csv
  - .\data\raw\traffic\a_year-by_id-new\9075.csv
  - .\data\raw\traffic\a_year-by_id-new\9076.csv
  - .\data\raw\traffic\a_year-by_id-new\9077.csv
  - .\data\raw\traffic\a_year-by_id-new\9078.csv
  - .\data\raw\traffic\a_year-by_id-new\9166.csv
  - .\data\raw\traffic\a_year-by_id-new\9167.csv
  - .\data\raw\traffic\a_year-by_id-new\9195.csv
  - .\data\raw\traffic\a_year-by_id-new\9196.csv
  - .\data\raw\traffic\a_year-by_id-new\9219.csv
  - .\data\raw\traffic\a_year-by_id-new\9220.csv
  - .\data\raw\traffic\a_year-by_id-new\9221.csv
  - .\data\raw\traffic\a_year-by_id-new\9222.csv
  - .\data\raw\traffic\a_year-by_id-new\9391.csv
  - .\data\raw\traffic\a_year-by_id-new\9392.csv
  - .\data\raw\traffic\a_year-by_id-new\9494.csv
  - .\data\raw\traffic\a_year-by_id-new\9495.csv
  - .\data\raw\traffic\a_year-by_id-new\9507.csv
  - .\data\raw\traffic\a_year-by_id-new\9533.csv
  - .\data\raw\traffic\a_year-by_id-new\9534.csv
  - .\data\raw\traffic\a_year-by_id-new\9562.csv
  - .\data\raw\traffic\a_year-by_id-new\9563.csv
  - .\data\raw\traffic\a_year-by_id-new\9564.csv
  - .\data\raw\traffic\a_year-by_id-new\9565.csv
  - .\data\raw\traffic\a_year-by_id-new\9566.csv
target: speed
date: date
features: kml_segment_id
time_id: time_id
start_time_id: 240
delimiter: "|"
split_feature: kml_segment_id
dir_as_feature: 0
split_dir_feature: 0
granularity: 5
time_format: 

year_start:
year_end:
month_start:
month_end:
day_start:
day_end:
hour_start: 4
hour_end: 22
minute_start:
minute_end:
