data: 
  - .\data\raw\traffic\a_year-by_id-has_rain\9093.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\531.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\532.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\9092.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8432.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3872.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\2859.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\287.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\288.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\289.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\533.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\534.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\587.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\588.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\642.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\886.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\887.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\946.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\947.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\948.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\1217.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\1218.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\1268.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\1269.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\1270.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\1298.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\1299.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\1310.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\1311.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\1455.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\1466.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\1510.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\1559.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\2077.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\2266.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\2267.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\2314.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\2378.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\2476.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\2477.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\2478.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\2479.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\2480.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\2481.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\2482.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\2521.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\2860.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\2861.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\2869.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\2982.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\2983.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\2984.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3009.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3010.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3011.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3102.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3103.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3104.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3105.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3106.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3107.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3108.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3109.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3140.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3141.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3142.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3143.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3367.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3368.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3369.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3370.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3371.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3372.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3373.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3374.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3375.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3376.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3377.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3378.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3379.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3380.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3381.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3382.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3383.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3384.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3385.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3386.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3387.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3388.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3389.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3390.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3410.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3411.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3412.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3413.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3414.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3447.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3448.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3449.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3450.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3452.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3453.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3454.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3546.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3547.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3692.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3693.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3759.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3760.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3780.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3781.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3782.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3838.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3839.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3840.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3870.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3871.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3923.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3924.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3952.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3953.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3954.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3955.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3956.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\3957.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\4105.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\4106.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\4107.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\4108.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\4121.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\4181.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\4224.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\4225.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\4414.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\4509.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\4510.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\4511.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\4512.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\4513.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\4514.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\4515.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\4550.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\4551.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\4552.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\4553.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\4662.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\4663.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\4664.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\4665.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\4931.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\5116.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\5117.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\5346.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\5388.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\5389.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\5390.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\5501.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\5741.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\5742.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\5743.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\5744.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\5764.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\5765.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\5780.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\5835.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\6332.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\6498.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\6499.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\6500.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\6501.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\6502.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\6553.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\6554.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\6864.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\6994.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\7164.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\7165.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\7166.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\7541.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\7578.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\7579.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\7580.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\7581.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\7582.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\7583.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\7584.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\7585.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\7654.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\7655.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\7656.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\7657.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\7658.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\7659.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\7665.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\7666.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\7667.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\7769.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\7770.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\7771.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\7772.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\7773.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\7774.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\7775.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\7776.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\7777.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\7778.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\7779.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\7780.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\7781.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\7782.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\7783.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\7784.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\7785.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\7806.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\7807.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\7808.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\7809.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\7810.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\7811.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\7812.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\7813.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\7814.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\7852.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\7853.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8117.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8125.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8126.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8127.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8141.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8282.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8388.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8389.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8390.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8391.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8474.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8514.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8515.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8578.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8579.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8580.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8584.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8585.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8586.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8587.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8641.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8642.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8643.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8644.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8645.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8646.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8647.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8648.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8649.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8650.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8651.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8652.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8653.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8654.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8655.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8656.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8657.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8658.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8659.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8660.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8661.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8662.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8679.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8680.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8681.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8729.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8776.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8777.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8778.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8786.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8787.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8814.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8920.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8925.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8926.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8927.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8928.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\8929.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\9038.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\9039.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\9075.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\9076.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\9077.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\9078.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\9166.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\9167.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\9195.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\9196.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\9219.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\9220.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\9221.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\9222.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\9391.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\9392.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\9494.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\9495.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\9507.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\9533.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\9534.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\9562.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\9563.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\9564.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\9565.csv
  - .\data\raw\traffic\a_year-by_id-has_rain\9566.csv
target: speed
date: date
features: 
  - kml_segment_id
  - rain
time_id: time_id
start_time_id: 240
delimiter: "|"
split_feature: kml_segment_id
dir_as_feature: 0
split_dir_feature: 0
granularity: 5
time_format: 

year_start:
year_end:
month_start:
month_end:
day_start:
day_end:
hour_start: 4
hour_end: 22
minute_start:
minute_end:
