data: 
  - .\data\raw\traffic\a_year-by_id-new\9194.csv
  - .\data\raw\traffic\a_year-by_id-new\1484.csv
  - .\data\raw\traffic\a_year-by_id-new\9265.csv
  - .\data\raw\traffic\a_year-by_id-new\9605.csv
  - .\data\raw\traffic\a_year-by_id-new\2130.csv
  - .\data\raw\traffic\a_year-by_id-new\4356.csv
  - .\data\raw\traffic\a_year-by_id-new\9352.csv
  - .\data\raw\traffic\a_year-by_id-new\1066.csv
  - .\data\raw\traffic\a_year-by_id-new\2227.csv
  - .\data\raw\traffic\a_year-by_id-new\380.csv
  - .\data\raw\traffic\a_year-by_id-new\659.csv
  - .\data\raw\traffic\a_year-by_id-new\9363.csv
  - .\data\raw\traffic\a_year-by_id-new\2755.csv
  - .\data\raw\traffic\a_year-by_id-new\1796.csv
  - .\data\raw\traffic\a_year-by_id-new\5280.csv
  - .\data\raw\traffic\a_year-by_id-new\4001.csv
  - .\data\raw\traffic\a_year-by_id-new\8951.csv
  - .\data\raw\traffic\a_year-by_id-new\1075.csv
  - .\data\raw\traffic\a_year-by_id-new\6296.csv
  - .\data\raw\traffic\a_year-by_id-new\664.csv
  - .\data\raw\traffic\a_year-by_id-new\2765.csv
  - .\data\raw\traffic\a_year-by_id-new\4917.csv
  - .\data\raw\traffic\a_year-by_id-new\1137.csv
  - .\data\raw\traffic\a_year-by_id-new\6185.csv
  - .\data\raw\traffic\a_year-by_id-new\6123.csv
  - .\data\raw\traffic\a_year-by_id-new\5712.csv
  - .\data\raw\traffic\a_year-by_id-new\8040.csv
  - .\data\raw\traffic\a_year-by_id-new\1453.csv
  - .\data\raw\traffic\a_year-by_id-new\8014.csv
  - .\data\raw\traffic\a_year-by_id-new\2088.csv
  - .\data\raw\traffic\a_year-by_id-new\1963.csv
  - .\data\raw\traffic\a_year-by_id-new\7180.csv
  - .\data\raw\traffic\a_year-by_id-new\4475.csv
  - .\data\raw\traffic\a_year-by_id-new\3335.csv
  - .\data\raw\traffic\a_year-by_id-new\2118.csv
  - .\data\raw\traffic\a_year-by_id-new\8858.csv
  - .\data\raw\traffic\a_year-by_id-new\2371.csv
  - .\data\raw\traffic\a_year-by_id-new\2548.csv
  - .\data\raw\traffic\a_year-by_id-new\208.csv
  - .\data\raw\traffic\a_year-by_id-new\3598.csv
  - .\data\raw\traffic\a_year-by_id-new\3939.csv
  - .\data\raw\traffic\a_year-by_id-new\8075.csv
  - .\data\raw\traffic\a_year-by_id-new\5397.csv
  - .\data\raw\traffic\a_year-by_id-new\3565.csv
  - .\data\raw\traffic\a_year-by_id-new\4922.csv
  - .\data\raw\traffic\a_year-by_id-new\203.csv
  - .\data\raw\traffic\a_year-by_id-new\3873.csv
  - .\data\raw\traffic\a_year-by_id-new\874.csv
  - .\data\raw\traffic\a_year-by_id-new\5697.csv
  - .\data\raw\traffic\a_year-by_id-new\6540.csv
  - .\data\raw\traffic\a_year-by_id-new\9695.csv
  - .\data\raw\traffic\a_year-by_id-new\7941.csv
  - .\data\raw\traffic\a_year-by_id-new\2834.csv
  - .\data\raw\traffic\a_year-by_id-new\61.csv
  - .\data\raw\traffic\a_year-by_id-new\8297.csv
  - .\data\raw\traffic\a_year-by_id-new\4427.csv
  - .\data\raw\traffic\a_year-by_id-new\4496.csv
  - .\data\raw\traffic\a_year-by_id-new\1520.csv
  - .\data\raw\traffic\a_year-by_id-new\4861.csv
  - .\data\raw\traffic\a_year-by_id-new\6166.csv
  - .\data\raw\traffic\a_year-by_id-new\9500.csv
  - .\data\raw\traffic\a_year-by_id-new\363.csv
  - .\data\raw\traffic\a_year-by_id-new\3708.csv
  - .\data\raw\traffic\a_year-by_id-new\8387.csv
  - .\data\raw\traffic\a_year-by_id-new\5574.csv
  - .\data\raw\traffic\a_year-by_id-new\9304.csv
  - .\data\raw\traffic\a_year-by_id-new\4429.csv
  - .\data\raw\traffic\a_year-by_id-new\7455.csv
  - .\data\raw\traffic\a_year-by_id-new\3458.csv
  - .\data\raw\traffic\a_year-by_id-new\3867.csv
  - .\data\raw\traffic\a_year-by_id-new\332.csv
  - .\data\raw\traffic\a_year-by_id-new\313.csv
  - .\data\raw\traffic\a_year-by_id-new\1850.csv
  - .\data\raw\traffic\a_year-by_id-new\691.csv
  - .\data\raw\traffic\a_year-by_id-new\7473.csv
  - .\data\raw\traffic\a_year-by_id-new\937.csv
  - .\data\raw\traffic\a_year-by_id-new\7397.csv
  - .\data\raw\traffic\a_year-by_id-new\2420.csv
  - .\data\raw\traffic\a_year-by_id-new\6968.csv
  - .\data\raw\traffic\a_year-by_id-new\6266.csv
  - .\data\raw\traffic\a_year-by_id-new\8510.csv
  - .\data\raw\traffic\a_year-by_id-new\3558.csv
  - .\data\raw\traffic\a_year-by_id-new\5047.csv
  - .\data\raw\traffic\a_year-by_id-new\4855.csv
  - .\data\raw\traffic\a_year-by_id-new\7721.csv
  - .\data\raw\traffic\a_year-by_id-new\7815.csv
  - .\data\raw\traffic\a_year-by_id-new\7453.csv
  - .\data\raw\traffic\a_year-by_id-new\1660.csv
  - .\data\raw\traffic\a_year-by_id-new\3113.csv
  - .\data\raw\traffic\a_year-by_id-new\1649.csv
  - .\data\raw\traffic\a_year-by_id-new\5100.csv
  - .\data\raw\traffic\a_year-by_id-new\399.csv
  - .\data\raw\traffic\a_year-by_id-new\3475.csv
  - .\data\raw\traffic\a_year-by_id-new\5595.csv
  - .\data\raw\traffic\a_year-by_id-new\4543.csv
  - .\data\raw\traffic\a_year-by_id-new\3243.csv
  - .\data\raw\traffic\a_year-by_id-new\8413.csv
  - .\data\raw\traffic\a_year-by_id-new\1289.csv
  - .\data\raw\traffic\a_year-by_id-new\2311.csv
  - .\data\raw\traffic\a_year-by_id-new\7499.csv
  - .\data\raw\traffic\a_year-by_id-new\4465.csv
  - .\data\raw\traffic\a_year-by_id-new\7503.csv
  - .\data\raw\traffic\a_year-by_id-new\8198.csv
  - .\data\raw\traffic\a_year-by_id-new\9235.csv
  - .\data\raw\traffic\a_year-by_id-new\8582.csv
  - .\data\raw\traffic\a_year-by_id-new\5042.csv
  - .\data\raw\traffic\a_year-by_id-new\9371.csv
  - .\data\raw\traffic\a_year-by_id-new\4098.csv
  - .\data\raw\traffic\a_year-by_id-new\8045.csv
  - .\data\raw\traffic\a_year-by_id-new\4112.csv
  - .\data\raw\traffic\a_year-by_id-new\1630.csv
  - .\data\raw\traffic\a_year-by_id-new\1026.csv
  - .\data\raw\traffic\a_year-by_id-new\2215.csv
  - .\data\raw\traffic\a_year-by_id-new\8913.csv
  - .\data\raw\traffic\a_year-by_id-new\2050.csv
  - .\data\raw\traffic\a_year-by_id-new\8568.csv
  - .\data\raw\traffic\a_year-by_id-new\7477.csv
  - .\data\raw\traffic\a_year-by_id-new\962.csv
  - .\data\raw\traffic\a_year-by_id-new\3403.csv
  - .\data\raw\traffic\a_year-by_id-new\7857.csv
  - .\data\raw\traffic\a_year-by_id-new\9258.csv
  - .\data\raw\traffic\a_year-by_id-new\2352.csv
  - .\data\raw\traffic\a_year-by_id-new\8618.csv
  - .\data\raw\traffic\a_year-by_id-new\7134.csv
  - .\data\raw\traffic\a_year-by_id-new\48.csv
  - .\data\raw\traffic\a_year-by_id-new\5269.csv
  - .\data\raw\traffic\a_year-by_id-new\4854.csv
  - .\data\raw\traffic\a_year-by_id-new\264.csv
  - .\data\raw\traffic\a_year-by_id-new\2034.csv
  - .\data\raw\traffic\a_year-by_id-new\7020.csv
  - .\data\raw\traffic\a_year-by_id-new\5787.csv
  - .\data\raw\traffic\a_year-by_id-new\9389.csv
  - .\data\raw\traffic\a_year-by_id-new\9633.csv
  - .\data\raw\traffic\a_year-by_id-new\7936.csv
  - .\data\raw\traffic\a_year-by_id-new\8673.csv
  - .\data\raw\traffic\a_year-by_id-new\2489.csv
  - .\data\raw\traffic\a_year-by_id-new\9444.csv
  - .\data\raw\traffic\a_year-by_id-new\3353.csv
  - .\data\raw\traffic\a_year-by_id-new\8847.csv
  - .\data\raw\traffic\a_year-by_id-new\3334.csv
  - .\data\raw\traffic\a_year-by_id-new\4810.csv
  - .\data\raw\traffic\a_year-by_id-new\5912.csv
  - .\data\raw\traffic\a_year-by_id-new\9436.csv
  - .\data\raw\traffic\a_year-by_id-new\5378.csv
  - .\data\raw\traffic\a_year-by_id-new\6625.csv
  - .\data\raw\traffic\a_year-by_id-new\5453.csv
  - .\data\raw\traffic\a_year-by_id-new\1334.csv
  - .\data\raw\traffic\a_year-by_id-new\8285.csv
  - .\data\raw\traffic\a_year-by_id-new\4194.csv
  - .\data\raw\traffic\a_year-by_id-new\6686.csv
target: speed
date: date
features: kml_segment_id
time_id: time_id
start_time_id: 240
delimiter: "|"
split_feature: kml_segment_id
dir_as_feature: 0
split_dir_feature: 0
granularity: 5
time_format: 

year_start:
year_end:
month_start:
month_end:
day_start:
day_end:
hour_start: 4
hour_end: 23
minute_start:
minute_end:
