data: .\data\raw\traffic\a_year-by_id-new\4844.csv
target: speed
date: date
features: kml_segment_id
time_id: time_id
start_time_id: 240
delimiter: "|"
split_feature: kml_segment_id
dir_as_feature: 0
split_dir_feature: 0
granularity: 5
time_format: 

year_start:
year_end:
month_start:
month_end:
day_start:
day_end:
hour_start: 4
hour_end: 22
minute_start:
minute_end:
