X_train: data/salinity/processed/615_csv-lag5-ahead1-offset1/X_train.npy
y_train: data/salinity/processed/615_csv-lag5-ahead1-offset1/y_train.npy
X_val: data/salinity/processed/615_csv-lag5-ahead1-offset1/X_val.npy
y_val: data/salinity/processed/615_csv-lag5-ahead1-offset1/y_val.npy
X_test: data/salinity/processed/615_csv-lag5-ahead1-offset1/X_test.npy
y_test: data/salinity/processed/615_csv-lag5-ahead1-offset1/y_test.npy
