data: data/salinity/raw/615.csv
target: average
date: dt
features: station
time_id:
delimiter: ","
split_feature: station # or None
dir_as_feature: 0
split_dir_feature: 0

year_start:
year_end:
month_start:
month_end:
day_start:
day_end:
hour_start:
hour_end:
minute_start:
minute_end: