data: .\data\traffic\raw\a_year
target: speed
date: date
features: current_geopath_id
time_id: time_id
delimiter: "|"
split_feature: current_geopath_id
dir_as_feature: 0
split_dir_feature: 0

year_start:
year_end:
month_start:
month_end:
day_start:
day_end:
hour_start:
hour_end:
minute_start:
minute_end:
