data: .\data\traffic\a_week\raw\vehicleworkgeopath_avg_speed-1.csv
target: speed
date: date
time_id: time_id
features: current_geopath_id
delimiter: "|"
split_feature: current_geopath_id # or None
dir_as_feature: 0
split_dir_feature: 0
