data: .\data\raw\benchmark\ETDataset\ETT-small
target: OT
date: date
time_id: 
start_time_id: 
features: 
  - HUFL
  - HULL
  - MUFL
  - MULL
  - LUFL
  - LULL
delimiter: ","
split_feature: 
dir_as_feature: 0
split_dir_feature: 0
time_format: 
granularity: 15

year_start:
year_end:
month_start:
month_end:
day_start:
day_end:
hour_start: 
hour_end: 
minute_start:
minute_end:
